<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <PackageId>OperationResult.Core</PackageId>
        <Version>1.0.0</Version>
        <Product>OperationResult.Core</Product>
        <Title>OperationResult.Core</Title>
        <Author>Vojislav Petkovic</Author>
        <Description>
            The OperationResult utility
            - Provides consistent, strongly-typed generic return objects throughout different layers of an application, from database queries in repositories to service-level operations
        </Description>
        <RepositoryUrl>https://github.com/vpetkovic/OperationResult</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>result;operationresult;.net;dotnet;c#;netstandard</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <PackageReleaseNotes>Retarget to .NET Standard 2.0/2.1 for broader compatibility</PackageReleaseNotes>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <None Update="icon.png">
        <Pack>True</Pack>
        <PackagePath></PackagePath>
      </None>
    </ItemGroup>

</Project>
